// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1RQkmoBqh9PS6M5Isbvzc46xyOzMkIkA',
    appId: '1:166950148075:web:31654c836a2e5aafcf2bae',
    messagingSenderId: '166950148075',
    projectId: 'vitiumv2-test',
    authDomain: 'vitiumv2-test.firebaseapp.com',
    storageBucket: 'vitiumv2-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCGScRLeU6Q15HqngrLTDn6bPPngFuuLM',
    appId: '1:166950148075:android:2b2e56e0f0d2419dcf2bae',
    messagingSenderId: '166950148075',
    projectId: 'vitiumv2-test',
    storageBucket: 'vitiumv2-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqrw_kwXrMRel9k8SbJaZX0GIL0J7jD7E',
    appId: '1:166950148075:ios:83a3e411824649dacf2bae',
    messagingSenderId: '166950148075',
    projectId: 'vitiumv2-test',
    storageBucket: 'vitiumv2-test.appspot.com',
    iosBundleId: 'com.vitium.vitium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqrw_kwXrMRel9k8SbJaZX0GIL0J7jD7E',
    appId: '1:166950148075:ios:6099aeb9dcf709eecf2bae',
    messagingSenderId: '166950148075',
    projectId: 'vitiumv2-test',
    storageBucket: 'vitiumv2-test.appspot.com',
    iosBundleId: 'com.vitium.vitium.RunnerTests',
  );
}
